# There is no secrets in the project

name: Java CI with Gradle

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17' ]
    name: Java ${{ matrix.Java }} build        
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: gradle
        check-latest: true
    - name: Build with Gradle
      run: ./gradlew build
